### PR TITLE
Rework of QtKnobs

### PR DESCRIPTION
**Pull request by strahlex**
- added minimumValue
- removed percent
- added prefix and suffix
- added stepSize
- bound many properties to be changeable at runtime

### CODE REVIEW

**Comment by strahlex** [comment]
@ashish157 I know this branch is not mergeable. Just tought a make a PR beacuse it looks like you are working on the same things as I did.b

**Comment by strahlex** [comment]
Here is what I am doing with QtKnobs: QtKnobs in Machineface

**Comment by ashish157** [comment]
I had already added minimumValue feature. The percent feature was introduced so that it can be used as a circular progressbar which also gives 'value' at each percent stepped. stepSize is a good feature I was also thinking something similar to it. I suppose I have to close it so that you continue with your changes in your personal repo. Consider me a newb in git. :)

**Comment by strahlex** [comment]
@ashish157 With the changed I added the knob works in both directions. So they can be used as progress bar as well. If you take a look at the ProgressBar and Slider implementation from Qt itselft you will see that they have the same interface. Qt is very well designed and most components ca be exchanged without many modifiactions to the properties.

Btw. Code School is good for learning git.

**Comment by ashish157** [comment]
Yes right. Hence I kept minimumValue, maximumValue and value properties earlier. I added Percent mode for the sake of a Circular progress bar where one can even set percent value (and minimumValue as 0 not required ). 
Thanks for the link.

**Pull request closed without merging**
